name: Fetch and preprocess Dubai
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  scheduled:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install p7zip-full wget libzip5
    - name: Fetch and preprocess Dubai
      run: |-
        cd scripts && ./dubai.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated Bot"
        git config user.email "info@interline.io"
        git add -A
        timestamp=$(date -u)
        git commit -m "Dubai feed fetched for this month" || exit 0
        git push
